### ISSUE TITLE
Unicorns :-)

### ISSUE THREAD

**Issue by cconstab** [michaelspiss/dart-utf7#1]
Nice work but of course I had to stumble into an issue..

A pair of Unicorns break on decode... Have not figured out why as yet..

```dart
import 'package:utf7/utf7.dart';

main() {
  String string = "🦄🦄";
  String encoded = Utf7.encode(string);
  String strongEncoded = Utf7.encodeAll(string);
  print("UTF-7 representation: $encoded");
  print("UTF-7 representation: $strongEncoded");
  String decoded = Utf7.decode(encoded);
  print("UTF-16 representation: $decoded");
}
```

> UTF-7 representation: +2D7dhNg+3YQ-
> UTF-7 representation: +2D7dhNg+3YQ-
> Unhandled exception:
> RangeError (index): Index out of range: index should be less than 5: 5
> #0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2209:7)
> #1      Utf7.decodeModifiedBase64 (package:utf7/src/utf7.dart:43:49)
> #2      Utf7.decode.<anonymous closure> (package:utf7/src/utf7.dart:99:14)
> #3      _StringBase.replaceAllMapped (dart:core-patch/string_patch.dart:734:35)
> #4      Utf7.decode (package:utf7/src/utf7.dart:96:19)
> #5      main (file:///C:/Users/colin/IdeaProjects/HEX/bin/main.dart:10:25)
> #6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
> #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
> 
> Process finished with exit code 255

**Comment by cconstab** [comment]
So on line 96 of utf7.dart
should read:-
    `    return string.replaceAllMapped(new RegExp(r"\+([A-Za-z0-9\/\+]*)-?"),`
not
    `return string.replaceAllMapped(new RegExp(r"\+([A-Za-z0-9]*)-?"),`
 
Also looks wrong here:- https://github.com/kkaefer/utf7/blob/master/utf7.js
on line 105 which I assume you ported your code from..

Thanks again for doing this work saved me doing it!

**Comment by michaelspiss** [comment]
First of all thank you for testing this case and providing a solution, I have completely forgotten about emojis and wouldn't have had time to find the mistake in the near future. You are absolutely correct, [rfc 2045](https://tools.ietf.org/html/rfc2045#section-6.8) lists `+` and `/` as part of the base64 alphabet, thus they should be included in the "set B" regex. I will publish a fix asap.

**Comment by michaelspiss** [comment]
> unicorns, mighty creatures that will break your code
